type User {
  uid: String!
  name: String!
  email: String!
  picture: String
}

type Game {
  date: String
  opposing_team: String
  opposing_runs: Int
  runs: Int
  uid: User
}

# Queries will set up an index within Fauna, which allow you to retrieve data based
# based on attributes.
# @see https://docs.fauna.com/fauna/current/api/fql/indexes?lang=javascript
type Query {
  users_by_uid(uid: String): [User!]
}
